### ISSUE TITLE
Large Multidimensional NDArray View

### ISSUE THREAD

**Issue by asti205** [microsoft/vscode-data-wrangler#467]
The tool doesn't provide a good view of large multidimensional arrays. If you have more than 2 dimensions, it just puts a list of elements into a 2D grid cell, which is not exactly what you want.
You want to go down in these dimensions too, explore them, and be able to see all the values along a dedicated dimension for a specific slice position. As it is, the tool is unusable for me personally for this purpose.

Please improve the tool for multidimensional NDArrays! The whole ML community will thank you, as indicated by other 1-star reviews (e.g. L on 8/5/2024). You mentioned it's in your backlog, but nothing happened since then. We need this, we cannot work with this tool, and there is no suitable alternative!

**Comment by wjfu99** [comment]
also support this feature, it's very important.
similar issues have been created in #312 #368

**Comment by pwang347** [comment]
Hi @asti205, @wjfu99 - thank you for providing valuable feedback on this!

We've just released in pre-release version 1.21.3 the ability to [slice](https://docs.python.org/3/reference/expressions.html#slicings) multidimensional data. You can access this new control next to the data shape:

<img width="261" alt="Image" src="https://github.com/user-attachments/assets/2a6f0c19-1191-4f99-8455-057d0194f1d2" />

> Note: This slice control isn't currently available for the new output renderer types we've added, but should be there soon.

It would be great if you could give this version a try and let us know if you have any suggestions for improvement. Hope this helps!

**Comment by wjfu99** [comment]
Hi @pwang347  thanks for your efforts on this feature, Im very appreciated.

I have tied the pre-released version, the function works well, seems support all python slice syntex. But I still have some suggestions:

1. In current version, the slice button seems only appear when watch a multidimensional Array, when I load a large 2D array, I can't  slice a smaller array to watch. Thus, I suggest to make the slice button works for all array, since we not only need to slice 3D array but also very large 2D array.

<img width="1202" alt="Image" src="https://github.com/user-attachments/assets/8b779439-f87d-4849-841f-11c53ac79eb0" />

2. The small slice window seems have some problems, when I click it then the window will disappear, so i have to move the cursor through direction keys.

https://github.com/user-attachments/assets/de391b16-aaaf-4403-b80b-2c617c7dc480

I will greatly appreciate it if you could look into these matters.

**Comment by pwang347** [comment]
Hi @wjfu99, I appreciate the quick help in trying the pre-release and for providing feedback comments! Both of these issues seem reasonable to fix. I've opened a PR addressing these and should be able to include it for the next pre-release.

Will let you know when this is available, thanks again!

**Comment by pwang347** [comment]
Hi @wjfu99, just letting you know that pre-release 1.21.4 fixes both items above. Thank you for the feedback!

**Comment by guoliangdeng** [comment]
The plugin lacks several key features
1. Unable to create a crosstab
2. Combine data vertically and horizontally (merge, concat)
3. Modify the data on the row that meets the conditions.
4. Use the APPLY function
Hopefully these features will be added.

**Comment by turbotimon** [comment]
@pwang347 create feature! I was waiting for it for some time. But somehow I can not see it, would you be so kind to explain me what I'm doing wrong? I'm on pre-release version **1.21.4**

E.g. open multidimensional csv, the "slicing"  does not appear when I click on "12 rows x 1 columns" or "Go to column":

![Image](https://github.com/user-attachments/assets/28461e60-ecdc-44b3-a46e-285a515c4c8a)

**Comment by pwang347** [comment]
> [@pwang347](https://github.com/pwang347) create feature! I was waiting for it for some time. But somehow I can not see it, would you be so kind to explain to me what I'm doing wrong? I'm on pre-release version **1.21.4**
> 
> E.g. open multidimensional csv, the "slicing" does not appear when I click on "12 rows x 1 columns" or "Go to column":
> 
> ![Image](https://github.com/user-attachments/assets/28461e60-ecdc-44b3-a46e-285a515c4c8a)

Hi @turbotimon, apologies for missing this! Currently this feature is only available for specific data types that support multi-dimensional data. Specifically, this list right now includes numpy ndarrays, pytorch tensors, tensorflow eagertensors, xarray dataarrays.

Generally, this feature needs to be able to determine the input N-D shape beforehand to be able to provide enough metadata for the control to work smoothly (e.g., input validation etc.). Out of curiosity also, is the CSV you provided actually parsing as a nested array? It looks like it's a string for me:

<img width="579" alt="Image" src="https://github.com/user-attachments/assets/94634f9f-64e3-4312-ab65-727f11fa36fa" />

For CSV:
```
a,b,c
1,[[108.51]],3
4,[[85.73]],6
```

**Comment by pwang347** [comment]
Hey @turbotimon - got it, and thanks for the clarification!

> I'm looking forward for the slicing feature for the new output render. My main use case would be to squeeze or flatten tensors for a better view.

Regarding this, wanted to share that we've just released pre-release version 1.21.5 which adds support for the slice control in the output renderer. It would be great if you could try it out and let us know if you have any feedback (since we plan to bring this experience to the stable version soon). Thanks!
